server:
  port: 8090
logging:
  file: C:\Git分支管理\modules\log.out
work-home: C:\Git分支管理\modules
projects:
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/GeoCloudActiveMQClient.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-3rd-framework.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-dispatch.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-telescopic.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-balance-core.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-balance-haproxy.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-core.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-databasegoods.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-dependence.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-dictionary.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-es-monitor-api.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-framework.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-gistools.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-log.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-manager-parent.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-parent.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-portal.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-processfactory.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-proxy.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-quartz.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-rest-manage.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-servicegoods.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-test.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-topology.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/core-components/geostack-orders-resolve.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/web-application/OperationCenter.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-cloud-cloudstack.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-cloud-manageone.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-cloud-openstack.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-cloud-ucloud.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-manageone-api.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-openstack-limits.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-openstack-serverinfo.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/cloud/geostack-ucloud-api.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/container/geostack-cloud-docker.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/container/geostack-cloud-libvirt.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/container/geostack-docker-api.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/common/geostack-cloud-parent.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/drive/common/geostack-cloud-common.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/zabbix/geostack-zabbix.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/zabbix/geostack-monitor-common.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/zabbix/geostack-monitor-zabbix.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/zabbix/geostack-spark-api.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/zabbix/geostack-zabbix-api.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/usersystem/Usersystem.git
  - git@yf-gitlab.geostar.com.cn:geostack2.5/source/cloud-platform/soms/geostack-soms.git
